# First-Time Book Project Setup

In this chapter, we will generate a pre-configured textbook template. Quarto makes creating a book incredibly easy because it has a built-in template that sets up the structure for you.

## Initialize the book structure
Make sure you are in your desired directory inside WSL. Run the following commands. These commands will create the textook project right there.
```bash
# Initialize a new Quarto book project skeleton
quarto create project book my-textbook
```

:::{.callout-note}
You create the book project exactly once. It acts as the "bookshelf" and container for your entire project. `book` is a specific project type that tells Quarto exactly how to structure and compile your files. If you type `quarto create project book`, Quarto knows you are writing a multi-page document. It automatically sets up features like:

- A sidebar menu for navigating chapters.
- Continuous page numbering across the whole project.
- Cross-referencing capabilities (so you can link Section 1 to Section 4 seamlessly).
- The ability to export everything into a single PDF or EPUB.

Chapters are just standard text files (like intro.qmd or chapter1.qmd) that live inside that book container. You don't need a command to create them; you just make a new text file inside VS Code whenever you want to start a new chapter!
:::


```bash
# Navigate into the project directory
cd my-textbook

# Initialize local workspace link to VS Code
code .
```
This creates a new folder called my-textbook inside your selected directory with everything you need:

+ _quarto.yml: The main configuration file (the "brain" of your book).
+ index.qmd: Your textbook's introduction page.
+ intro.qmd, summary.qmd: Example chapters.

Open this new folder inside VS Code. You can write standard Markdown in these files, and insert any code by enclosing it in 3 back tick blocks (e.g., ```git add .```), and LaTeX math by enclosing it in $ blocks (e.g., $E = mc^2$).

## Clean Up and Configure Files
Inside VS Code, look at the Explorer sidebar. You will see several files. Let's configure them.

### Create a `.gitignore`:
Create a new file named .gitignore in the root folder and paste these lines so you don't accidental upload temporary files to GitHub. Following is an example of content in a typical `.gitignore` file

```gitignore
/.quarto/
/_book
*.deb
/_site/
/.ipynb_checkpoints/
*.csv
*.xlsx
*.rds
*.pkl
*.mp4

**/*.quarto_ipynb
```

### Update Book Settings (`_quarto.yml`)
Open _quarto.yml. This file dictates the layout of your book. Replace its contents with your requirements. Metadata options available are given here. [YAML options](https://quarto-tdg.org/yaml). 
Think of the options available as 

+ Project Metadata - to define project type `book` 
+ Document Metadata - to define `title`, `author`, `language`, etc.
+ Output formats - `html`, `pdf`, `epub`, `docx`
+ Lists - multiple values using YAML sequence syntax
Supported datatypes include, `string`, `boolean`, `numbers`, `list`, `array`, literal blocks

:::{.callout-note}
## Chapters
When you have your book outline and chapters decided, open your `_quarto.yml` file in VS Code and replace the chapters: section so it maps out your new book structure cleanly.
For instance, you could update the `_quarto.yml` file like this
```bash
book:
  ...
  chapters:
    - index.qmd
    - 01-prereqs.qmd
    - 02-project-setup.qmd
    - 03-github-integration.qmd
    - 04-deployment.qmd
    - 05-ongoing-management.qmd
...
```
Make sure to generate those blank `.qmd` files in your folder so Quarto doesn't throw a "file not found" error.
Run this single command block in your terminal to create all five chapter files instantly
```bash
touch 01-prereqs.qmd 02-project-setup.qmd 03-github-integration.qmd 04-deployment.qmd 05-ongoing-management.qmd
```
:::

### Writing Content
Open index.qmd (this is your book's homepage / Preface). Replace the text with a quick welcome. Try out writing `code` and $LaTex$ formulae and other `markdown` syntax

:::{.callout-tip}
## Writing New Chapters
Structure the _quarto.yml file to organize your textbook's chapters, sections, and appendix
:::