project:
  type: book
  output-dir: _book

book:
  title: "Living Textbooks"
  subtitle: "A Handbook for authors to use WSL, Quarto, and GitHub Pages to create and maintain Living Textbooks"
  author: "Sridhar Ramachandran"
  date: last-modified
  date-format: "MMMM DD, YYYY"
  sidebar:
    style: "docked"
    search: true
  chapters:
    - index.qmd
    - changelog.qmd
    - intro.qmd
    - 01-prereqs.qmd
    - 02-project-setup.qmd
    - 03-github-integration.qmd
    - 04-deployment.qmd
    - 05-ongoing-management.qmd
    - 99-appendix.qmd
    - keywords.qmd
  page-footer: 
    left: "© 2026 Sridhar Ramachandran. All rights reserved."
    right: "Built with [Quarto](https://quarto.org/)"

bibliography: references.bib

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    code-copy: true
    # html-math-method: katex
  pdf:
    documentclass: scrreprt
    toc: true
    toc-depth: 2